CREATE DATABASE IF NOT EXISTS `WECAREDB`;
USE `WECAREDB`;

DROP TABLE IF EXISTS `PATIENT`;

CREATE TABLE `PATIENT` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CNP` int(13) NOT NULL,
  `FIRSTNAME` varchar(100) NOT NULL,
  `LASTNAME` varchar(100) NOT NULL,
  `GP` varchar(100) NOT NULL,
  `HOSPITAL` varchar(100) NOT NULL,
  `COUNTY` varchar(100) NOT NULL,
  `CITY` varchar(100) NOT NULL,
  `ADDRESS` varchar(100) NOT NULL,
  `PHONE` int(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `DUEDATE` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
